# top level stuff you probably don't need to touch
highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://benreichert.com
baseurl: /
title: Ben Reichert
author: Ben Reichert
description: Personal blog, projects, etc.
avatar: profile.jpg
email: ben<at>benreichert.com
github: tgjamin # username
twitter: tgjamin
linkedin: benreichert
